---
- name: Uninstall old versions of docker
  apt:
    name:
      - docker
      - docker-ce
      - docker-ce-cli
      - docker-engine
      - docker-compose
      - docker.io
      - containerd
      - containerd.io
      - runc
    state: absent

- name: Install prerequisites
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    update_cache: yes

- name: Add apt key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Add apt repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    filename: docker

- name: Install required packages (latest)
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - docker-compose
      - containerd.io
    update_cache: yes
  when: docker_version == "latest"

- name: Install required packages (specified)
  apt:
    name:
      - docker-ce={{ docker_version }}
      - docker-ce-cli={{ docker_version }}
      - docker-compose
      - containerd.io

- name: Write docker config
  copy:
    content: "{{ docker_daemon_config | to_nice_json }}\n"
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 0640
  notify: Reload docker

- name: Add users to the docker group
  user:
    name: "{{ item }}"
    groups: docker
    append: true
  with_items:
    - "{{ docker_privileged_users }}"

- meta: flush_handlers

- name: Enable docker service
  service:
    name: docker
    enabled: True
    state: started
